GET http://localhost:8000

###
GET http://localhost:8000/1395

###
POST http://localhost:8000
Content-Type: application/json

{
    "title": "title",
    "body": "body"
}

###
PATCH  http://localhost:8000
Content-Type: application/json

{
    "id": 6023,
    "title": "updated"
}

###
DELETE http://localhost:8000/6023